/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog/skus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Configure Sku */
        post: operations["configure_sku_v1_catalog_skus_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog/skus/{sku_id}/unit-conversions/{conversion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Unit Conversion */
        put: operations["update_unit_conversion_v1_catalog_skus__sku_id__unit_conversions__conversion_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Customers */
        get: operations["search_customers_v1_customers_get"];
        put?: never;
        /** Create Customer */
        post: operations["create_customer_v1_customers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/customers/{customer_id}/addresses/{address_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Customer Address */
        put: operations["update_customer_address_v1_customers__customer_id__addresses__address_key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/customers/{customer_id}/addresses/{address_key}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Customer Address Version */
        get: operations["get_customer_address_version_v1_customers__customer_id__addresses__address_key__versions__version__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/customers/{customer_id}/credit-approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Customer Credit */
        post: operations["approve_customer_credit_v1_customers__customer_id__credit_approvals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/inventory/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Availability */
        get: operations["search_availability_v1_inventory_availability_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/inventory/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Stock Location */
        post: operations["create_stock_location_v1_inventory_locations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/inventory/opening-stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Opening Stock */
        post: operations["post_opening_stock_v1_inventory_opening_stock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/inventory/projections/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rebuild Inventory Projections */
        post: operations["rebuild_inventory_projections_v1_inventory_projections_rebuild_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organization/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bootstrap Organization */
        post: operations["bootstrap_organization_v1_organization_bootstrap_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organization/branches/{branch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Branch Lifecycle */
        patch: operations["update_branch_lifecycle_v1_organization_branches__branch_id__patch"];
        trace?: never;
    };
    "/v1/organization/company": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Company */
        patch: operations["update_company_v1_organization_company_patch"];
        trace?: never;
    };
    "/v1/organization/role-templates/{role_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Configure Role Template */
        put: operations["configure_role_template_v1_organization_role_templates__role_code__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organization/scope": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Organization Scope */
        get: operations["get_organization_scope_v1_organization_scope_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organization/users/{subject}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Configure User */
        put: operations["configure_user_v1_organization_users__subject__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organization/warehouses/{warehouse_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Warehouse Lifecycle */
        patch: operations["update_warehouse_lifecycle_v1_organization_warehouses__warehouse_id__patch"];
        trace?: never;
    };
    "/v1/platform/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ping */
        post: operations["ping_v1_platform_ping_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session */
        get: operations["session_v1_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddressInput */
        AddressInput: {
            /** Address Key */
            address_key: string;
            /** City */
            city: string;
            /** Country Code */
            country_code: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "billing" | "delivery";
            /** Line 1 */
            line_1: string;
            /** Line 2 */
            line_2?: string | null;
            /** Postal Code */
            postal_code: string;
            /** Region */
            region: string;
        };
        /** AddressResponse */
        AddressResponse: {
            /** Address Key */
            address_key: string;
            /**
             * Address Version Id
             * Format: uuid
             */
            address_version_id: string;
            /** City */
            city: string;
            /** Country Code */
            country_code: string;
            /** Is Current */
            is_current: boolean;
            /**
             * Kind
             * @enum {string}
             */
            kind: "billing" | "delivery";
            /** Line 1 */
            line_1: string;
            /** Line 2 */
            line_2: string | null;
            /** Postal Code */
            postal_code: string;
            /** Region */
            region: string;
            /** Version */
            version: number;
        };
        /** AddressUpdateResponse */
        AddressUpdateResponse: {
            address: components["schemas"]["AddressResponse"];
            /**
             * Customer Id
             * Format: uuid
             */
            customer_id: string;
            /** Customer Version */
            customer_version: number;
        };
        /** ApprovalAuthorityInput */
        "ApprovalAuthorityInput-Input": {
            /** Branch Code */
            branch_code: string;
            /** Capability */
            capability: string;
            /**
             * Maker Checker Required
             * @default true
             */
            maker_checker_required: boolean;
            /** Maximum Amount */
            maximum_amount?: number | string | null;
            /** Maximum Percentage */
            maximum_percentage?: number | string | null;
        };
        /** ApprovalAuthorityInput */
        "ApprovalAuthorityInput-Output": {
            /** Branch Code */
            branch_code: string;
            /** Capability */
            capability: string;
            /**
             * Maker Checker Required
             * @default true
             */
            maker_checker_required: boolean;
            /** Maximum Amount */
            maximum_amount?: string | null;
            /** Maximum Percentage */
            maximum_percentage?: string | null;
        };
        /** AvailabilityItem */
        AvailabilityItem: {
            /** Available */
            available: string;
            /** Base Currency */
            base_currency: string;
            /** Base Stocking Unit */
            base_stocking_unit: string;
            /**
             * Custody
             * @enum {string}
             */
            custody: "available" | "quarantine";
            /** Expiration Control */
            expiration_control: boolean;
            /** Expiration Date */
            expiration_date: string | null;
            /** Location Code */
            location_code: string;
            /** Lot Code */
            lot_code: string | null;
            /** Moving Average Unit Cost */
            moving_average_unit_cost: string;
            /** On Hand */
            on_hand: string;
            /** Reserved */
            reserved: string;
            /** Serial Numbers */
            serial_numbers: string[];
            /** Sku Code */
            sku_code: string;
            /**
             * Sku Id
             * Format: uuid
             */
            sku_id: string;
            /** Sku Name */
            sku_name: string;
            /**
             * Tracking Policy
             * @enum {string}
             */
            tracking_policy: "untracked" | "lot" | "serial";
            /** Warehouse Code */
            warehouse_code: string;
            /**
             * Warehouse Id
             * Format: uuid
             */
            warehouse_id: string;
            /** Warehouse Inventory Value */
            warehouse_inventory_value: string;
        };
        /** AvailabilityResponse */
        AvailabilityResponse: {
            /** Items */
            items: components["schemas"]["AvailabilityItem"][];
            /** Total */
            total: number;
        };
        /** BarcodeInput */
        BarcodeInput: {
            /** Barcode */
            barcode: string;
            /** Unit Code */
            unit_code?: string | null;
        };
        /** BarcodeResponse */
        BarcodeResponse: {
            /** Barcode */
            barcode: string;
            /**
             * Barcode Mapping Id
             * Format: uuid
             */
            barcode_mapping_id: string;
            /** Unit Code */
            unit_code: string;
        };
        /** BranchInput */
        BranchInput: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Warehouses */
            warehouses: components["schemas"]["WarehouseInput"][];
        };
        /** BranchLifecycleResponse */
        BranchLifecycleResponse: {
            /**
             * Branch Id
             * Format: uuid
             */
            branch_id: string;
            /** Code */
            code: string;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
            /** Version */
            version: number;
        };
        /** BranchResponse */
        BranchResponse: {
            /**
             * Branch Id
             * Format: uuid
             */
            branch_id: string;
            /** Code */
            code: string;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
            /** Version */
            version: number;
            /** Warehouses */
            warehouses: components["schemas"]["WarehouseResponse"][];
        };
        /** CompanyInput */
        CompanyInput: {
            /** Base Currency */
            base_currency: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
        };
        /** CompanyResponse */
        CompanyResponse: {
            /** Base Currency */
            base_currency: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Version */
            version: number;
        };
        /** ConfigureRoleTemplateCommand */
        ConfigureRoleTemplateCommand: {
            /** Capabilities */
            capabilities: string[];
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Name */
            name: string;
        };
        /** ConfigureSkuCommand */
        ConfigureSkuCommand: {
            /** Barcodes */
            barcodes?: components["schemas"]["BarcodeInput"][];
            /** Base Stocking Unit */
            base_stocking_unit: string;
            /** Conversions */
            conversions?: components["schemas"]["ConversionInput"][];
            /**
             * Expiration Control
             * @default false
             */
            expiration_control: boolean;
            /** Product Code */
            product_code: string;
            /** Product Name */
            product_name: string;
            /** Sku Code */
            sku_code: string;
            /** Sku Name */
            sku_name: string;
            /**
             * Tracking Policy
             * @enum {string}
             */
            tracking_policy: "untracked" | "lot" | "serial";
        };
        /** ConfigureUserCommand */
        ConfigureUserCommand: {
            /** Approval Authorities */
            approval_authorities?: components["schemas"]["ApprovalAuthorityInput-Input"][];
            /** Branch Codes */
            branch_codes?: string[];
            /** Display Name */
            display_name: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Is Operations Administrator
             * @default false
             */
            is_operations_administrator: boolean;
            /** Role Template Codes */
            role_template_codes?: string[];
            /** Warehouse Codes */
            warehouse_codes?: string[];
        };
        /** ContactInput */
        ContactInput: {
            /** Email */
            email?: string | null;
            /** Name */
            name: string;
            /** Phone */
            phone?: string | null;
            /** Role */
            role: string;
        };
        /** ContactResponse */
        ContactResponse: {
            /**
             * Contact Id
             * Format: uuid
             */
            contact_id: string;
            /** Email */
            email: string | null;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
            /** Phone */
            phone: string | null;
            /** Role */
            role: string;
            /** Version */
            version: number;
        };
        /** ConversionInput */
        ConversionInput: {
            /** Base Quantity */
            base_quantity: number | string;
            /**
             * Effective From
             * Format: date
             */
            effective_from: string;
            /** Effective To */
            effective_to?: string | null;
            /** Unit Code */
            unit_code: string;
        };
        /** ConversionResponse */
        ConversionResponse: {
            /** Base Quantity */
            base_quantity: string;
            /**
             * Effective From
             * Format: date
             */
            effective_from: string;
            /** Effective To */
            effective_to: string | null;
            /** Unit Code */
            unit_code: string;
            /**
             * Unit Conversion Id
             * Format: uuid
             */
            unit_conversion_id: string;
            /** Version */
            version: number;
        };
        /** CreateCustomerCommand */
        CreateCustomerCommand: {
            /** Account Number */
            account_number: string;
            /** Addresses */
            addresses: components["schemas"]["AddressInput"][];
            /**
             * Branch Id
             * Format: uuid
             */
            branch_id: string;
            /** Contacts */
            contacts?: components["schemas"]["ContactInput"][];
            /**
             * Credit Hold
             * @default false
             */
            credit_hold: boolean;
            /** Credit Limit */
            credit_limit?: number | string | null;
            /** Legal Name */
            legal_name: string;
            /** Payment Terms */
            payment_terms: string;
            /**
             * Payment Timing Policy
             * @enum {string}
             */
            payment_timing_policy: "prepaid" | "cash_on_delivery" | "on_account";
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "inactive" | "prospect";
        };
        /** CreateLocationCommand */
        CreateLocationCommand: {
            /** Code */
            code: string;
            /**
             * Custody
             * @enum {string}
             */
            custody: "available" | "quarantine";
            /** Name */
            name: string;
            /**
             * Warehouse Id
             * Format: uuid
             */
            warehouse_id: string;
        };
        /** CreditApprovalCommand */
        CreditApprovalCommand: {
            /** Reason */
            reason: string;
        };
        /** CreditApprovalResponse */
        CreditApprovalResponse: {
            /** Approved By */
            approved_by: string;
            /**
             * Credit Approval Id
             * Format: uuid
             */
            credit_approval_id: string;
            /** Credit Hold */
            credit_hold: boolean;
            /** Credit Limit */
            credit_limit: string;
            /**
             * Customer Id
             * Format: uuid
             */
            customer_id: string;
            /** Customer Version */
            customer_version: number;
            /** Reason */
            reason: string;
        };
        /** CustomerResponse */
        CustomerResponse: {
            /** Account Number */
            account_number: string;
            /** Addresses */
            addresses: components["schemas"]["AddressResponse"][];
            /**
             * Branch Id
             * Format: uuid
             */
            branch_id: string;
            /** Contacts */
            contacts: components["schemas"]["ContactResponse"][];
            /** Credit Hold */
            credit_hold: boolean;
            /** Credit Limit */
            credit_limit: string | null;
            /**
             * Customer Id
             * Format: uuid
             */
            customer_id: string;
            /** Legal Name */
            legal_name: string;
            /** Payment Terms */
            payment_terms: string;
            /**
             * Payment Timing Policy
             * @enum {string}
             */
            payment_timing_policy: "prepaid" | "cash_on_delivery" | "on_account";
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "inactive" | "prospect";
            /** Version */
            version: number;
        };
        /** CustomerSearchItem */
        CustomerSearchItem: {
            /** Account Number */
            account_number: string;
            /**
             * Branch Id
             * Format: uuid
             */
            branch_id: string;
            /** Credit Hold */
            credit_hold: boolean;
            /**
             * Customer Id
             * Format: uuid
             */
            customer_id: string;
            /** Legal Name */
            legal_name: string;
            /**
             * Payment Timing Policy
             * @enum {string}
             */
            payment_timing_policy: "prepaid" | "cash_on_delivery" | "on_account";
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "inactive" | "prospect";
            /** Version */
            version: number;
        };
        /** CustomerSearchResponse */
        CustomerSearchResponse: {
            /** Items */
            items: components["schemas"]["CustomerSearchItem"][];
            /** Total */
            total: number;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Correlation Id */
            correlation_id: string;
            /** Message */
            message: string;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** LifecycleCommand */
        LifecycleCommand: {
            /** Is Active */
            is_active: boolean;
        };
        /** LiveResponse */
        LiveResponse: {
            /** Service */
            service: string;
            /** Status */
            status: string;
        };
        /** LocationResponse */
        LocationResponse: {
            /** Code */
            code: string;
            /**
             * Custody
             * @enum {string}
             */
            custody: "available" | "quarantine";
            /**
             * Location Id
             * Format: uuid
             */
            location_id: string;
            /** Name */
            name: string;
            /** Version */
            version: number;
            /**
             * Warehouse Id
             * Format: uuid
             */
            warehouse_id: string;
        };
        /** OpeningStockCommand */
        OpeningStockCommand: {
            /** Expiration Date */
            expiration_date?: string | null;
            /**
             * Location Id
             * Format: uuid
             */
            location_id: string;
            /** Lot Code */
            lot_code?: string | null;
            /** Quantity */
            quantity: number | string;
            /** Serial Numbers */
            serial_numbers?: string[];
            /**
             * Sku Id
             * Format: uuid
             */
            sku_id: string;
            /** Source Reference */
            source_reference: string;
            /** Unit Code */
            unit_code: string;
            /** Unit Cost */
            unit_cost: number | string;
            /**
             * Warehouse Id
             * Format: uuid
             */
            warehouse_id: string;
        };
        /** OpeningStockResponse */
        OpeningStockResponse: {
            /** Base Currency */
            base_currency: string;
            /** Conversion Snapshot */
            conversion_snapshot: {
                [key: string]: string;
            };
            /** Entered Unit */
            entered_unit: string;
            /**
             * Location Id
             * Format: uuid
             */
            location_id: string;
            /**
             * Movement Id
             * Format: uuid
             */
            movement_id: string;
            /** Moving Average Unit Cost */
            moving_average_unit_cost: string;
            /** Quantity Base */
            quantity_base: string;
            /**
             * Sku Id
             * Format: uuid
             */
            sku_id: string;
            /** Source Reference */
            source_reference: string;
            /** Value Delta */
            value_delta: string;
            /**
             * Warehouse Id
             * Format: uuid
             */
            warehouse_id: string;
        };
        /** OrganizationBootstrapCommand */
        OrganizationBootstrapCommand: {
            /** Branches */
            branches: components["schemas"]["BranchInput"][];
            company: components["schemas"]["CompanyInput"];
            /** Role Templates */
            role_templates: components["schemas"]["RoleTemplateInput"][];
            /** Users */
            users: components["schemas"]["UserInput"][];
        };
        /** OrganizationBootstrapResponse */
        OrganizationBootstrapResponse: {
            /** Branches */
            branches: components["schemas"]["BranchResponse"][];
            company: components["schemas"]["CompanyResponse"];
            /** Configured Users */
            configured_users: number;
        };
        /** OrganizationScopeResponse */
        OrganizationScopeResponse: {
            /** Branches */
            branches: components["schemas"]["ScopeBranchResponse"][];
            /** Capabilities */
            capabilities: string[];
            user: components["schemas"]["ScopeUserResponse"];
            /** Warehouses */
            warehouses: components["schemas"]["ScopeWarehouseResponse"][];
        };
        /** PingCommand */
        PingCommand: {
            /** Message */
            message: string;
        };
        /** PingResponse */
        PingResponse: {
            /** Command Id */
            command_id: string;
            /** Message */
            message: string;
        };
        /** ProjectionRebuildResponse */
        ProjectionRebuildResponse: {
            /** Availability Rows */
            availability_rows: number;
            /** Valuation Rows */
            valuation_rows: number;
        };
        /** ReadyResponse */
        ReadyResponse: {
            /** Database */
            database: string;
            /** Service */
            service: string;
            /** Status */
            status: string;
        };
        /** RoleTemplateInput */
        RoleTemplateInput: {
            /** Capabilities */
            capabilities: string[];
            /** Code */
            code: string;
            /** Name */
            name: string;
        };
        /** RoleTemplateResponse */
        RoleTemplateResponse: {
            /** Capabilities */
            capabilities: string[];
            /** Code */
            code: string;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
            /** Version */
            version: number;
        };
        /** ScopeBranchResponse */
        ScopeBranchResponse: {
            /**
             * Branch Id
             * Format: uuid
             */
            branch_id: string;
            /** Code */
            code: string;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
            /** Version */
            version: number;
        };
        /** ScopeUserResponse */
        ScopeUserResponse: {
            /** Display Name */
            display_name: string;
            /** Is Operations Administrator */
            is_operations_administrator: boolean;
            /** Subject */
            subject: string;
        };
        /** ScopeWarehouseResponse */
        ScopeWarehouseResponse: {
            /**
             * Branch Id
             * Format: uuid
             */
            branch_id: string;
            /** Code */
            code: string;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
            /** Version */
            version: number;
            /**
             * Warehouse Id
             * Format: uuid
             */
            warehouse_id: string;
        };
        /** SessionResponse */
        SessionResponse: {
            /** Database */
            database: string;
            /** Service */
            service: string;
            user: components["schemas"]["SessionUserResponse"];
        };
        /** SessionUserResponse */
        SessionUserResponse: {
            /** Capabilities */
            capabilities: string[];
            /** Display Name */
            display_name: string;
            /** Subject */
            subject: string;
        };
        /** SkuResponse */
        SkuResponse: {
            /** Barcodes */
            barcodes: components["schemas"]["BarcodeResponse"][];
            /** Base Stocking Unit */
            base_stocking_unit: string;
            /** Conversions */
            conversions: components["schemas"]["ConversionResponse"][];
            /** Expiration Control */
            expiration_control: boolean;
            /** Product Code */
            product_code: string;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Product Name */
            product_name: string;
            /** Sku Code */
            sku_code: string;
            /**
             * Sku Id
             * Format: uuid
             */
            sku_id: string;
            /** Sku Name */
            sku_name: string;
            /**
             * Tracking Policy
             * @enum {string}
             */
            tracking_policy: "untracked" | "lot" | "serial";
            /** Version */
            version: number;
        };
        /** UpdateAddressCommand */
        UpdateAddressCommand: {
            /** City */
            city: string;
            /** Country Code */
            country_code: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "billing" | "delivery";
            /** Line 1 */
            line_1: string;
            /** Line 2 */
            line_2?: string | null;
            /** Postal Code */
            postal_code: string;
            /** Region */
            region: string;
        };
        /** UpdateCompanyCommand */
        UpdateCompanyCommand: {
            /** Base Currency */
            base_currency: string;
            /** Name */
            name: string;
        };
        /** UpdateConversionCommand */
        UpdateConversionCommand: {
            /** Base Quantity */
            base_quantity: number | string;
            /**
             * Effective From
             * Format: date
             */
            effective_from: string;
            /** Effective To */
            effective_to?: string | null;
        };
        /** UserConfigurationResponse */
        UserConfigurationResponse: {
            /** Approval Authorities */
            approval_authorities: components["schemas"]["ApprovalAuthorityInput-Output"][];
            /** Branch Codes */
            branch_codes: string[];
            /** Display Name */
            display_name: string;
            /** Is Active */
            is_active: boolean;
            /** Is Operations Administrator */
            is_operations_administrator: boolean;
            /** Role Template Codes */
            role_template_codes: string[];
            /** Subject */
            subject: string;
            /** Version */
            version: number;
            /** Warehouse Codes */
            warehouse_codes: string[];
        };
        /** UserInput */
        UserInput: {
            /** Approval Authorities */
            approval_authorities?: components["schemas"]["ApprovalAuthorityInput-Input"][];
            /** Branch Codes */
            branch_codes?: string[];
            /** Display Name */
            display_name: string;
            /**
             * Is Operations Administrator
             * @default false
             */
            is_operations_administrator: boolean;
            /** Role Template Codes */
            role_template_codes?: string[];
            /** Subject */
            subject: string;
            /** Warehouse Codes */
            warehouse_codes?: string[];
        };
        /** WarehouseInput */
        WarehouseInput: {
            /** Code */
            code: string;
            /** Name */
            name: string;
        };
        /** WarehouseResponse */
        WarehouseResponse: {
            /** Code */
            code: string;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
            /** Version */
            version: number;
            /**
             * Warehouse Id
             * Format: uuid
             */
            warehouse_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveResponse"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    configure_sku_v1_catalog_skus_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigureSkuCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkuResponse"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    update_unit_conversion_v1_catalog_skus__sku_id__unit_conversions__conversion_id__put: {
        parameters: {
            query?: never;
            header: {
                "If-Match": number;
                "Idempotency-Key": string;
            };
            path: {
                sku_id: string;
                conversion_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateConversionCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversionResponse"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    search_customers_v1_customers_get: {
        parameters: {
            query?: {
                query?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerSearchResponse"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_customer_v1_customers_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCustomerCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerResponse"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    update_customer_address_v1_customers__customer_id__addresses__address_key__put: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: number | null;
                "Idempotency-Key"?: string | null;
            };
            path: {
                customer_id: string;
                address_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAddressCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressUpdateResponse"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_customer_address_version_v1_customers__customer_id__addresses__address_key__versions__version__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: string;
                address_key: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressResponse"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    approve_customer_credit_v1_customers__customer_id__credit_approvals_post: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: number | null;
                "Idempotency-Key"?: string | null;
            };
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreditApprovalCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreditApprovalResponse"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    search_availability_v1_inventory_availability_get: {
        parameters: {
            query?: {
                query?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityResponse"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_stock_location_v1_inventory_locations_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLocationCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationResponse"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    post_opening_stock_v1_inventory_opening_stock_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpeningStockCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpeningStockResponse"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    rebuild_inventory_projections_v1_inventory_projections_rebuild_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectionRebuildResponse"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    bootstrap_organization_v1_organization_bootstrap_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationBootstrapCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationBootstrapResponse"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    update_branch_lifecycle_v1_organization_branches__branch_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: number | null;
                "Idempotency-Key"?: string | null;
            };
            path: {
                branch_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LifecycleCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchLifecycleResponse"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    update_company_v1_organization_company_patch: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: number | null;
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCompanyCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyResponse"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    configure_role_template_v1_organization_role_templates__role_code__put: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: number | null;
                "Idempotency-Key"?: string | null;
            };
            path: {
                role_code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigureRoleTemplateCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleTemplateResponse"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_organization_scope_v1_organization_scope_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationScopeResponse"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    configure_user_v1_organization_users__subject__put: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: number | null;
                "Idempotency-Key"?: string | null;
            };
            path: {
                subject: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigureUserCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserConfigurationResponse"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    update_warehouse_lifecycle_v1_organization_warehouses__warehouse_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: number | null;
                "Idempotency-Key"?: string | null;
            };
            path: {
                warehouse_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LifecycleCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarehouseResponse"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    ping_v1_platform_ping_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PingCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PingResponse"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    session_v1_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stable TradeFlow error envelope. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
